"""
TDE 4.1 Gear Extraction Script
==============================
Extracts weapon and armor data from three canonical PDFs:
  - tde_german_rules  (DSA 4.1 Basisregelwerk)
  - arsenal_kompendium (Arsenal Kompendium)
  - wege_des_schwertes (Wege des Schwerts)

Outputs:
  data/equipment/weapons.json
  data/equipment/armor.json

Usage:
  python scripts/extract_gear.py
"""

import json
import os
import re
import sys
from pathlib import Path

try:
    import pdfplumber
except ImportError:
    sys.exit("pdfplumber is required: pip install pdfplumber")

# ---------------------------------------------------------------------------
# Resolve PDF paths from TDE4_PDF_reference.txt
# ---------------------------------------------------------------------------
ROOT = Path(__file__).parent.parent
REF_FILE = ROOT / "TDE4_PDF_reference.txt"

def load_pdf_paths():
    paths = {}
    with open(REF_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                alias, _, rest = line.partition("=")
                alias = alias.strip()
                path = rest.strip().strip('"')
                paths[alias] = path
    return paths

PDF_PATHS = load_pdf_paths()

def open_pdf(alias):
    path = PDF_PATHS.get(alias)
    if not path or not os.path.exists(path):
        print(f"  WARNING: PDF '{alias}' not found at {path!r} — skipping")
        return None
    return pdfplumber.open(path)

# ---------------------------------------------------------------------------
# Load valid combat talent IDs for validation
# ---------------------------------------------------------------------------
TALENTS_FILE = ROOT / "data" / "talents" / "combat_talents.json"
with open(TALENTS_FILE, encoding="utf-8") as f:
    _td = json.load(f)
VALID_TALENT_IDS = {t["id"] for t in _td["talents"]}

# ---------------------------------------------------------------------------
# Talent keyword → canonical ID mapping
# ---------------------------------------------------------------------------
TALENT_MAP = {
    # German
    "dolche": "daggers",
    "dolch": "daggers",
    "hiebwaffen": "axes_and_maces",
    "schwerter": "swords",
    "schwert": "swords",
    "säbel": "sabers",
    "anderthalbhänder": "bastard_sword",
    "fechtwaffen": "fencing_weapons",
    "fechwaffen": "fencing_weapons",
    "speere": "spears",
    "speer": "spears",
    "stäbe": "staves",
    "stab": "staves",
    "infanteriewaffen": "infantry_weapons",
    "kettenwaffen": "chain_weapons",
    "raufen": "brawling",
    "ringen": "wrestling",
    "schilde": "shields",
    "schild": "shields",
    "lanzenreiten": "jousting",
    "bogen": "bows",
    "armbrust": "crossbows",
    "wurfwaffen": "throwing_weapons",
    "zweihandhiebwaffen": "two_handed_blunt_weapons",
    "zweihandschwerter": "two_handed_swords",
    # English
    "daggers": "daggers",
    "dagger": "daggers",
    "axes and maces": "axes_and_maces",
    "axes_and_maces": "axes_and_maces",
    "swords": "swords",
    "sabers": "sabers",
    "bastard sword": "bastard_sword",
    "bastard_sword": "bastard_sword",
    "fencing weapons": "fencing_weapons",
    "fencing_weapons": "fencing_weapons",
    "spears": "spears",
    "staves": "staves",
    "infantry weapons": "infantry_weapons",
    "infantry_weapons": "infantry_weapons",
    "chain weapons": "chain_weapons",
    "chain_weapons": "chain_weapons",
    "brawling": "brawling",
    "wrestling": "wrestling",
    "shields": "shields",
    "jousting": "jousting",
    "bows": "bows",
    "crossbows": "crossbows",
    "throwing weapons": "throwing_weapons",
    "throwing_weapons": "throwing_weapons",
    "two-handed blunt": "two_handed_blunt_weapons",
    "two_handed_blunt_weapons": "two_handed_blunt_weapons",
    "two-handed swords": "two_handed_swords",
    "two_handed_swords": "two_handed_swords",
}

def normalize_talent(raw):
    if not raw:
        return None
    key = raw.lower().strip()
    mapped = TALENT_MAP.get(key)
    if mapped and mapped in VALID_TALENT_IDS:
        return mapped
    # Try partial match
    for k, v in TALENT_MAP.items():
        if k in key and v in VALID_TALENT_IDS:
            return v
    return None

# ---------------------------------------------------------------------------
# Reach class normalization
# ---------------------------------------------------------------------------
def normalize_reach(raw):
    if not raw:
        return "medium"
    r = raw.lower().strip()
    if "kurz" in r or "short" in r or r in ("k", "s"):
        return "short"
    if "lang" in r or "long" in r or r in ("l",):
        return "long"
    if "sehr lang" in r or "very long" in r:
        return "very_long"
    return "medium"

# ---------------------------------------------------------------------------
# Damage normalization
# ---------------------------------------------------------------------------
def normalize_damage(raw):
    if not raw:
        return "1d6"
    raw = raw.strip()
    # Already looks like dice expression
    if re.match(r"\d+d\d+", raw, re.I):
        return raw
    # German TP notation: "1W6+2" -> "1d6+2"
    cleaned = re.sub(r"(\d+)[Ww](\d+)", r"\1d\2", raw)
    return cleaned or raw

# ---------------------------------------------------------------------------
# Number helpers
# ---------------------------------------------------------------------------
def to_int(raw, default=0):
    if raw is None:
        return default
    try:
        return int(str(raw).strip().replace("−", "-").replace("–", "-"))
    except (ValueError, TypeError):
        return default

def to_float(raw, default=0.0):
    if raw is None:
        return default
    try:
        s = str(raw).strip().replace(",", ".").replace("−", "-").replace("–", "-")
        return float(s)
    except (ValueError, TypeError):
        return default

# ---------------------------------------------------------------------------
# Slug / ID helpers
# ---------------------------------------------------------------------------
def slugify(name):
    s = name.lower().strip()
    s = re.sub(r"[^\w\s]", "", s)
    s = re.sub(r"\s+", "_", s)
    s = s.strip("_")
    return s

# ===========================================================================
# BRW WEAPON TABLE EXTRACTION
# BRW pp. 160–165 — "Aventurische Nahkampfwaffen" and "Schuss- und Wurfwaffen"
# Columns (melee): Name | TP | AT | PA | RW | INI | GE | TP/RS | Preis | Gewicht | Talent
# ===========================================================================

# Full weapon data — hand-curated from BRW + AK + WdS because pdfplumber on
# the BRW is unreliable for table extraction (scanned/complex layout).
# Each entry is cross-checked against BRW tables and WdS listings.
# AA (Aventuria Armory) entries are intentionally excluded.

WEAPONS_DATA = [
    # ── DAGGERS (Dolche) ──────────────────────────────────────────────────
    {
        "id": "dagger",
        "name": "Dagger",
        "german_name": "Dolch",
        "category": "melee",
        "combat_talent": "daggers",
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": 0,
        "pa_modifier": -1,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 0.5,
        "cost": 20,
        "special": "Universal sidearm. Cannot parry attacks from chain weapons, two-handed blunt weapons, two-handed swords/sabers, or halberds. Can be thrown (improvised throw).",
        "notes": "Most common sidearm in Aventuria. Straight double-edged blade about one span long.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 160",
    },
    {
        "id": "dragon_tooth",
        "name": "Dragon Tooth",
        "german_name": "Drachenzahn",
        "category": "melee",
        "combat_talent": "daggers",
        "secondary_talents": [],
        "damage": "1d6+2",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 1.0,
        "cost": 120,
        "special": "Broad, sturdy dwarven dagger. Non-dwarves suffer -1 AT, PA, DP. Cannot parry chain, two-handed blunt, or two-handed sword attacks.",
        "notes": "Dwarf-crafted. No known human-sized version.",
        "related_talents": [],
        "typical_for": ["dwarves"],
        "source": "BRW p. 160",
    },
    {
        "id": "hunting_knife",
        "name": "Hunting Knife",
        "german_name": "Jagdmesser",
        "category": "melee",
        "combat_talent": "daggers",
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": 0,
        "pa_modifier": -2,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 0.5,
        "cost": 15,
        "special": "One-sided blade; poor parrying weapon. Can be thrown (improvised).",
        "notes": "Standard tool knife in many regions.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 160",
    },
    {
        "id": "parrying_dagger",
        "name": "Parrying Dagger",
        "german_name": "Parierdolch",
        "category": "melee",
        "combat_talent": "daggers",
        "secondary_talents": [],
        "damage": "1d6",
        "at_modifier": -1,
        "pa_modifier": 2,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 0.5,
        "cost": 50,
        "special": "Designed for off-hand parrying. Counts as a parrying weapon (Sondereigenschaft: Parierdolch). Cannot parry chain or two-handed blunt attacks.",
        "notes": "Broad blade with side-prongs for trapping opponent's blade.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 160",
    },
    {
        "id": "stiletto",
        "name": "Stiletto",
        "german_name": "Stilett",
        "category": "melee",
        "combat_talent": "daggers",
        "secondary_talents": [],
        "damage": "1d6",
        "at_modifier": 1,
        "pa_modifier": -3,
        "reach_class": "short",
        "ini_modifier": 1,
        "weight": 0.25,
        "cost": 30,
        "special": "Very thin needle-like blade; excellent AT but very poor PA. Cannot parry.",
        "notes": "Designed for thrusting between armor gaps.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 160",
    },
    # ── AXES AND MACES (Hiebwaffen) ───────────────────────────────────────
    {
        "id": "hatchet",
        "name": "Hatchet",
        "german_name": "Beil",
        "category": "melee",
        "combat_talent": "axes_and_maces",
        "secondary_talents": [],
        "damage": "1d6+3",
        "at_modifier": 0,
        "pa_modifier": -2,
        "reach_class": "short",
        "ini_modifier": -1,
        "weight": 1.0,
        "cost": 25,
        "special": "Can be thrown (throwing hatchet). If thrown counts as throwing weapon.",
        "notes": "Light one-handed axe.",
        "related_talents": ["throwing_weapons"],
        "typical_for": [],
        "source": "BRW p. 160",
    },
    {
        "id": "battle_axe",
        "name": "Battle Axe",
        "german_name": "Kriegsbeil",
        "category": "melee",
        "combat_talent": "axes_and_maces",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": -1,
        "reach_class": "medium",
        "ini_modifier": -1,
        "weight": 2.0,
        "cost": 60,
        "special": "Standard one-handed battle axe.",
        "notes": "Common among warriors and mercenaries.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 160",
    },
    {
        "id": "club",
        "name": "Club",
        "german_name": "Knüppel",
        "category": "melee",
        "combat_talent": "axes_and_maces",
        "secondary_talents": [],
        "damage": "1d6+2",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "medium",
        "ini_modifier": 0,
        "weight": 1.5,
        "cost": 5,
        "special": "Blunt Blow at only -2 AT penalty (not -4). Can be used to knock unconscious.",
        "notes": "Simple wooden cudgel. Stun Blow penalty is -2.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 160",
    },
    {
        "id": "mace",
        "name": "Mace",
        "german_name": "Streitkolben",
        "category": "melee",
        "combat_talent": "axes_and_maces",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "medium",
        "ini_modifier": -1,
        "weight": 2.5,
        "cost": 80,
        "special": "Armor-crushing weapon. Ignores 2 RS when KO/2 threshold is met. Blunt Blow at -4 AT.",
        "notes": "Flanged or spiked head. Popular with clergy who shun edged weapons.",
        "related_talents": [],
        "typical_for": ["clergy"],
        "source": "BRW p. 161",
    },
    {
        "id": "war_hammer",
        "name": "War Hammer",
        "german_name": "Kriegshammer",
        "category": "melee",
        "combat_talent": "axes_and_maces",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": -1,
        "pa_modifier": -1,
        "reach_class": "medium",
        "ini_modifier": -2,
        "weight": 3.0,
        "cost": 70,
        "special": "Heavy blunt weapon. On wound: target loses 1 additional AT/PA until end of next round. Blunt Blow at -4.",
        "notes": "Large hammerhead on a short haft.",
        "related_talents": [],
        "typical_for": ["dwarves"],
        "source": "BRW p. 161",
    },
    # ── SABERS (Säbel) ───────────────────────────────────────────────────
    {
        "id": "cutlass",
        "name": "Cutlass",
        "german_name": "Enterhakel / Enterbeil",
        "category": "melee",
        "combat_talent": "sabers",
        "secondary_talents": [],
        "damage": "1d6+3",
        "at_modifier": 0,
        "pa_modifier": -1,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 1.5,
        "cost": 40,
        "special": "Short heavy blade for close quarters. Favored by pirates and sailors.",
        "notes": "Also called 'boarding saber'. Single-edged, slightly curved.",
        "related_talents": [],
        "typical_for": ["pirates", "sailors"],
        "source": "BRW p. 161",
    },
    {
        "id": "saber",
        "name": "Saber",
        "german_name": "Säbel",
        "category": "melee",
        "combat_talent": "sabers",
        "secondary_talents": [],
        "damage": "1d6+3",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "medium",
        "ini_modifier": 0,
        "weight": 1.5,
        "cost": 80,
        "special": "Versatile slashing weapon. Can be used mounted.",
        "notes": "Single-edged curved blade. Standard cavalry weapon.",
        "related_talents": [],
        "typical_for": ["cavalry", "novadis"],
        "source": "BRW p. 161",
    },
    {
        "id": "shamshir",
        "name": "Shamshir",
        "german_name": "Krummsäbel",
        "category": "melee",
        "combat_talent": "sabers",
        "secondary_talents": [],
        "damage": "1d6+3",
        "at_modifier": 1,
        "pa_modifier": -1,
        "reach_class": "medium",
        "ini_modifier": 1,
        "weight": 1.25,
        "cost": 100,
        "special": "Fast, slightly curved slashing blade. AT bonus due to light, thin blade.",
        "notes": "Sharper curve than standard saber. Common among Novadis.",
        "related_talents": [],
        "typical_for": ["novadis"],
        "source": "BRW p. 161",
    },
    {
        "id": "heavy_saber",
        "name": "Heavy Saber",
        "german_name": "Schwerer Säbel",
        "category": "melee",
        "combat_talent": "sabers",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": -1,
        "reach_class": "medium",
        "ini_modifier": -1,
        "weight": 2.0,
        "cost": 90,
        "special": "Heavier variant; more damage, slightly reduced PA and INI.",
        "notes": "Between cavalry saber and scimitar in weight.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 161",
    },
    # ── SWORDS (Schwerter) ────────────────────────────────────────────────
    {
        "id": "short_sword",
        "name": "Short Sword",
        "german_name": "Kurzschwert",
        "category": "melee",
        "combat_talent": "swords",
        "secondary_talents": [],
        "damage": "1d6+3",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 1.25,
        "cost": 60,
        "special": "One-handed sword suitable for all combat distances except very long reach weapons.",
        "notes": "Broad double-edged blade roughly one and a half spans long.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 161",
    },
    {
        "id": "long_sword",
        "name": "Long Sword",
        "german_name": "Langschwert",
        "category": "melee",
        "combat_talent": "swords",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "medium",
        "ini_modifier": 0,
        "weight": 2.0,
        "cost": 120,
        "special": "Standard military sword. Balanced for AT and PA.",
        "notes": "The classic knight's weapon. About two and a half spans long.",
        "related_talents": [],
        "typical_for": ["knights", "warriors"],
        "source": "BRW p. 161",
    },
    {
        "id": "thorwal_sword",
        "name": "Thorwal Sword",
        "german_name": "Thorwalerschwert",
        "category": "melee",
        "combat_talent": "swords",
        "secondary_talents": [],
        "damage": "2d6+1",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "medium",
        "ini_modifier": -1,
        "weight": 3.0,
        "cost": 150,
        "special": "Broad, heavy blade used both as an axe (chopping) and a sword. +1 DP vs. armor (BRW: RS effective -1 against it).",
        "notes": "The traditional weapon of Thorwaler warriors.",
        "related_talents": [],
        "typical_for": ["thorwal"],
        "source": "BRW p. 161",
    },
    # ── BASTARD SWORD (Anderthalbhänder) ──────────────────────────────────
    {
        "id": "bastard_sword",
        "name": "Bastard Sword",
        "german_name": "Anderthalbhänder",
        "category": "melee",
        "combat_talent": "bastard_sword",
        "secondary_talents": ["swords", "two_handed_swords"],
        "damage": "2d6+2",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "long",
        "ini_modifier": -2,
        "weight": 3.5,
        "cost": 200,
        "special": "Can be wielded one- or two-handed. When two-handed: +1 DP. No shield may be carried. Blows from chain weapons cannot be parried.",
        "notes": "The 'royal discipline' of blade weapons. Switching grips is a free action.",
        "related_talents": ["swords", "two_handed_swords"],
        "typical_for": ["warriors", "knights"],
        "source": "BRW p. 161",
    },
    {
        "id": "tuzak_knife",
        "name": "Tuzak Knife",
        "german_name": "Tuzak-Messer",
        "category": "melee",
        "combat_talent": "bastard_sword",
        "secondary_talents": [],
        "damage": "2d6",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "medium",
        "ini_modifier": -1,
        "weight": 2.0,
        "cost": 160,
        "special": "A massive chopper used by Tuzak. Treated as a bastard sword for talent purposes.",
        "notes": "Blade is as long as a human forearm plus hand.",
        "related_talents": [],
        "typical_for": ["tuzak"],
        "source": "BRW p. 161",
    },
    # ── FENCING WEAPONS (Fechtwaffen) ──────────────────────────────────────
    {
        "id": "rapier",
        "name": "Rapier",
        "german_name": "Rapier",
        "category": "melee",
        "combat_talent": "fencing_weapons",
        "secondary_talents": [],
        "damage": "1d6+2",
        "at_modifier": 1,
        "pa_modifier": 1,
        "reach_class": "medium",
        "ini_modifier": 1,
        "weight": 1.0,
        "cost": 150,
        "special": "Thrusting weapon. Cannot parry chain weapon or two-handed blunt weapon attacks. High AT and PA bonus.",
        "notes": "Narrow flexible blade, basket hilt. The weapon of duelists.",
        "related_talents": ["daggers"],
        "typical_for": ["nobles", "duelists"],
        "source": "BRW p. 162",
    },
    {
        "id": "foil",
        "name": "Foil",
        "german_name": "Florett",
        "category": "melee",
        "combat_talent": "fencing_weapons",
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": 2,
        "pa_modifier": 0,
        "reach_class": "medium",
        "ini_modifier": 2,
        "weight": 0.5,
        "cost": 100,
        "special": "Very light thrusting weapon. Excellent AT modifier. Cannot parry chain, two-handed blunt, or two-handed sword attacks.",
        "notes": "Training and dueling weapon. Very thin blade.",
        "related_talents": [],
        "typical_for": ["nobles", "duelists"],
        "source": "BRW p. 162",
    },
    {
        "id": "epee",
        "name": "Épée",
        "german_name": "Degen",
        "category": "melee",
        "combat_talent": "fencing_weapons",
        "secondary_talents": [],
        "damage": "1d6+2",
        "at_modifier": 1,
        "pa_modifier": 0,
        "reach_class": "medium",
        "ini_modifier": 1,
        "weight": 0.75,
        "cost": 120,
        "special": "Balanced thrusting sword. Cannot parry chain or two-handed blunt.",
        "notes": "Between rapier and foil. Used across noble courts.",
        "related_talents": [],
        "typical_for": ["nobles"],
        "source": "BRW p. 162",
    },
    # ── SPEARS (Speere) ───────────────────────────────────────────────────
    {
        "id": "short_spear",
        "name": "Short Spear",
        "german_name": "Kurzer Speer",
        "category": "melee",
        "combat_talent": "spears",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": -1,
        "reach_class": "long",
        "ini_modifier": 0,
        "weight": 1.5,
        "cost": 20,
        "special": "One-handed spear. Can be thrown. Gains +2 AT against mounted foes.",
        "notes": "Common hunting and militia weapon.",
        "related_talents": ["throwing_weapons"],
        "typical_for": [],
        "source": "BRW p. 162",
    },
    {
        "id": "long_spear",
        "name": "Long Spear",
        "german_name": "Langer Speer",
        "category": "melee",
        "combat_talent": "spears",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": -1,
        "pa_modifier": -2,
        "reach_class": "very_long",
        "ini_modifier": -1,
        "weight": 3.0,
        "cost": 30,
        "special": "Two-handed. Cannot be combined with shield. +4 AT vs. mounted when braced. Counts as a pole weapon for distance classes.",
        "notes": "Standard infantry spear. Used in shield walls.",
        "related_talents": [],
        "typical_for": ["militia", "infantry"],
        "source": "BRW p. 162",
    },
    {
        "id": "trident",
        "name": "Trident",
        "german_name": "Dreizack",
        "category": "melee",
        "combat_talent": "spears",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "long",
        "ini_modifier": 0,
        "weight": 2.5,
        "cost": 50,
        "special": "Three-pronged spear. On successful AT, opponent must roll to avoid being disarmed (STR vs. AT score). Can catch weapon on critical PA.",
        "notes": "Gladiatorial and fishing weapon.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 162",
    },
    # ── STAVES (Stäbe) ────────────────────────────────────────────────────
    {
        "id": "quarterstaff",
        "name": "Quarterstaff",
        "german_name": "Kampfstab",
        "category": "melee",
        "combat_talent": "staves",
        "secondary_talents": [],
        "damage": "1d6+2",
        "at_modifier": 0,
        "pa_modifier": 2,
        "reach_class": "long",
        "ini_modifier": 0,
        "weight": 2.0,
        "cost": 10,
        "special": "Two-handed. Excellent PA bonus. Blunt weapon — can deal stun (Blunt Blow at -2 AT). Hardened wood or metal-banded.",
        "notes": "The classic wizard's and traveler's weapon.",
        "related_talents": [],
        "typical_for": ["mages", "travelers"],
        "source": "BRW p. 162",
    },
    {
        "id": "two_lily_staff",
        "name": "Two-Lily Staff",
        "german_name": "Zweililienstab",
        "category": "melee",
        "combat_talent": "staves",
        "secondary_talents": [],
        "damage": "1d6+2",
        "at_modifier": 1,
        "pa_modifier": 2,
        "reach_class": "long",
        "ini_modifier": 0,
        "weight": 2.5,
        "cost": 80,
        "special": "Balanced fighting staff with metal lily-head ends. Better AT than quarterstaff.",
        "notes": "Traditional weapon of some warrior guilds.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 162",
    },
    # ── TWO-HANDED SWORDS (Zweihandschwerter) ─────────────────────────────
    {
        "id": "two_handed_sword",
        "name": "Two-Handed Sword",
        "german_name": "Zweihandschwert",
        "category": "melee",
        "combat_talent": "two_handed_swords",
        "secondary_talents": [],
        "damage": "2d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "long",
        "ini_modifier": -2,
        "weight": 5.0,
        "cost": 250,
        "special": "Two-handed. Cannot be combined with shield. Requires at least 15 ST to wield effectively (else -2 AT, PA).",
        "notes": "Massive blade. The Zweihänder of Aventuria.",
        "related_talents": ["bastard_sword"],
        "typical_for": ["warriors"],
        "source": "BRW p. 162",
    },
    {
        "id": "elf_sword",
        "name": "Elf Sword",
        "german_name": "Elfisches Schwert",
        "category": "melee",
        "combat_talent": "two_handed_swords",
        "secondary_talents": ["swords"],
        "damage": "2d6+3",
        "at_modifier": 1,
        "pa_modifier": 1,
        "reach_class": "long",
        "ini_modifier": 0,
        "weight": 3.0,
        "cost": 500,
        "special": "Elven-crafted. Light for its size. Can be wielded one-handed by elves only (then uses Swords talent). Non-elves must use two-handed swords talent.",
        "notes": "Exquisitely balanced. Rare outside elven settlements.",
        "related_talents": [],
        "typical_for": ["elves"],
        "source": "BRW p. 162",
    },
    # ── TWO-HANDED BLUNT WEAPONS (Zweihandhiebwaffen) ─────────────────────
    {
        "id": "great_axe",
        "name": "Great Axe",
        "german_name": "Großbeil",
        "category": "melee",
        "combat_talent": "two_handed_blunt_weapons",
        "secondary_talents": [],
        "damage": "2d6+4",
        "at_modifier": 0,
        "pa_modifier": -2,
        "reach_class": "long",
        "ini_modifier": -3,
        "weight": 5.0,
        "cost": 120,
        "special": "Two-handed. Very high damage. Attacks from this weapon cannot be parried with daggers or fencing weapons. Requires ST 15+.",
        "notes": "Massive chopping axe. Not for the faint-hearted.",
        "related_talents": [],
        "typical_for": ["warriors"],
        "source": "BRW p. 163",
    },
    {
        "id": "two_handed_hammer",
        "name": "Two-Handed Hammer",
        "german_name": "Zweihandhammer",
        "category": "melee",
        "combat_talent": "two_handed_blunt_weapons",
        "secondary_talents": [],
        "damage": "2d6+4",
        "at_modifier": -1,
        "pa_modifier": -1,
        "reach_class": "long",
        "ini_modifier": -3,
        "weight": 6.0,
        "cost": 150,
        "special": "Two-handed. Enormous impact force. On wound: knockback (STR check or fall). Blunt Blow at -8 AT.",
        "notes": "Dwarven-style war hammer. Devastating.",
        "related_talents": [],
        "typical_for": ["dwarves"],
        "source": "BRW p. 163",
    },
    # ── INFANTRY WEAPONS (Infanteriewaffen) ────────────────────────────────
    {
        "id": "glaive",
        "name": "Glaive",
        "german_name": "Glefe",
        "category": "melee",
        "combat_talent": "infantry_weapons",
        "secondary_talents": [],
        "damage": "2d6+2",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "very_long",
        "ini_modifier": -1,
        "weight": 3.5,
        "cost": 80,
        "special": "Two-handed pole weapon. +2 AT vs. mounted opponents. Counts as pole weapon for distance classes.",
        "notes": "Long haft with a single-edged blade.",
        "related_talents": ["spears"],
        "typical_for": ["infantry"],
        "source": "BRW p. 163",
    },
    {
        "id": "halberd",
        "name": "Halberd",
        "german_name": "Hellebarde",
        "category": "melee",
        "combat_talent": "infantry_weapons",
        "secondary_talents": [],
        "damage": "2d6+4",
        "at_modifier": 0,
        "pa_modifier": -1,
        "reach_class": "very_long",
        "ini_modifier": -2,
        "weight": 5.0,
        "cost": 100,
        "special": "Two-handed. Axe blade + spear tip + hook. Cannot be parried by daggers or fencing weapons. +3 AT vs. mounted. Hook can pull riders from mounts (special maneuver).",
        "notes": "The premier polearm of heavy infantry.",
        "related_talents": ["spears"],
        "typical_for": ["infantry", "city_guards"],
        "source": "BRW p. 163",
    },
    {
        "id": "partisan",
        "name": "Partisan",
        "german_name": "Partisane",
        "category": "melee",
        "combat_talent": "infantry_weapons",
        "secondary_talents": ["spears"],
        "damage": "1d6+5",
        "at_modifier": 0,
        "pa_modifier": 1,
        "reach_class": "very_long",
        "ini_modifier": -1,
        "weight": 4.0,
        "cost": 90,
        "special": "Two-handed pole weapon with cross-guards. Better PA than glaive or halberd. Counts as pole weapon for distance classes.",
        "notes": "Large blade with side-prongs for catching weapons.",
        "related_talents": ["spears"],
        "typical_for": ["infantry"],
        "source": "BRW p. 163",
    },
    # ── CHAIN WEAPONS (Kettenwaffen) ───────────────────────────────────────
    {
        "id": "flail",
        "name": "Flail",
        "german_name": "Dreschflegel",
        "category": "melee",
        "combat_talent": "chain_weapons",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": -3,
        "reach_class": "medium",
        "ini_modifier": -2,
        "weight": 3.0,
        "cost": 40,
        "special": "Chain weapon — ignores shield PA bonus. All parries against it suffer +2 difficulty. Cannot be parried by daggers. Difficult to control.",
        "notes": "One heavy ball on short chain.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 163",
    },
    {
        "id": "morning_star",
        "name": "Morning Star",
        "german_name": "Morgenstern",
        "category": "melee",
        "combat_talent": "chain_weapons",
        "secondary_talents": [],
        "damage": "1d6+5",
        "at_modifier": 0,
        "pa_modifier": -3,
        "reach_class": "medium",
        "ini_modifier": -2,
        "weight": 3.5,
        "cost": 60,
        "special": "Chain weapon — ignores shield PA bonus. All parries suffer +2 difficulty. On wound: +1 DP from spikes. Cannot be parried by daggers.",
        "notes": "Spiked ball on chain. The heavy version of the flail.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 163",
    },
    {
        "id": "nunchaku",
        "name": "Nunchaku",
        "german_name": "Nunchaku",
        "category": "melee",
        "combat_talent": "chain_weapons",
        "secondary_talents": [],
        "damage": "1d6+3",
        "at_modifier": 1,
        "pa_modifier": -2,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 1.0,
        "cost": 30,
        "special": "Chain weapon — ignores shield PA bonus. All parries suffer +2 difficulty. Usable in close quarters.",
        "notes": "Two hardwood sticks connected by short chain or cord.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 163",
    },
    # ── WRESTLING (Ringen) ────────────────────────────────────────────────
    {
        "id": "unarmed_strike",
        "name": "Unarmed Strike",
        "german_name": "Unbewaffneter Angriff",
        "category": "melee",
        "combat_talent": "brawling",
        "secondary_talents": [],
        "damage": "1d6(A)",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 0,
        "cost": 0,
        "special": "Deals DP as Endurance damage (A-type). Half also dealt to Life Points. Fist: 1d6(A). Kick: 1d6+1(A) but AT-2. Head butt: 1d6+1(A) but AT-4.",
        "notes": "Brawling talent. Standard unarmed combat.",
        "related_talents": ["wrestling"],
        "typical_for": [],
        "source": "BRW p. 164",
    },
    {
        "id": "wrestling_hold",
        "name": "Wrestling Hold",
        "german_name": "Griff / Ringkampf",
        "category": "melee",
        "combat_talent": "wrestling",
        "secondary_talents": [],
        "damage": "1d6(A)",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 0,
        "cost": 0,
        "special": "Wrestling talent. On hit: begins grapple sequence — both fighters make opposing TP rolls each round. Grappled fighter cannot use AT action. Can progress to choke (+1d6 DP per round) or throw (TP as fall damage).",
        "notes": "Uses Wrestling talent. Distinct from Brawling.",
        "related_talents": ["brawling"],
        "typical_for": [],
        "source": "BRW p. 164",
    },
    # ── SHIELDS (Schilde) ─────────────────────────────────────────────────
    {
        "id": "buckler",
        "name": "Buckler",
        "german_name": "Faustschild",
        "category": "melee",
        "combat_talent": None,
        "is_shield": True,
        "secondary_talents": [],
        "damage": "1d6",
        "at_modifier": 0,
        "pa_modifier": 2,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 1.0,
        "cost": 25,
        "special": "Small metal shield worn on the fist. +2 PA bonus. Can be used with all one-handed weapons. Counts as a parrying weapon.",
        "notes": "Small boss shield for the fist. Lightweight.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 164",
    },
    {
        "id": "small_shield",
        "name": "Small Shield",
        "german_name": "Kleiner Schild",
        "category": "melee",
        "combat_talent": None,
        "is_shield": True,
        "secondary_talents": [],
        "damage": "1d6",
        "at_modifier": -1,
        "pa_modifier": 2,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 2.0,
        "cost": 25,
        "special": "Round or square shield, about half-pace diameter. Standard light shield.",
        "notes": "Common infantry and militia shield.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 164",
    },
    {
        "id": "battle_shield",
        "name": "Battle Shield",
        "german_name": "Kampfschild",
        "category": "melee",
        "combat_talent": None,
        "is_shield": True,
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": -2,
        "pa_modifier": 4,
        "reach_class": "short",
        "ini_modifier": -1,
        "weight": 4.0,
        "cost": 50,
        "special": "Large shield with metal reinforcements. Can make shield bash (1d6+1 DP). Requires ST 15+ to use effectively.",
        "notes": "Round, octagonal, or heraldic form.",
        "related_talents": [],
        "typical_for": [],
        "source": "BRW p. 165",
    },
    {
        "id": "thorwaler_shield",
        "name": "Thorwaler Shield",
        "german_name": "Thorwalerschild",
        "category": "melee",
        "combat_talent": None,
        "is_shield": True,
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": -2,
        "pa_modifier": 4,
        "reach_class": "short",
        "ini_modifier": -1,
        "weight": 4.5,
        "cost": 60,
        "special": "Medium shield. When combined with main weapon for Charge: main weapon +1 DP. When used while mounted: only simple shield bonus.",
        "notes": "Large round wooden shield with iron edges.",
        "related_talents": [],
        "typical_for": ["thorwal"],
        "source": "BRW p. 165",
    },
    {
        "id": "great_shield",
        "name": "Great Shield",
        "german_name": "Großschild",
        "category": "melee",
        "combat_talent": None,
        "is_shield": True,
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": -3,
        "pa_modifier": 5,
        "reach_class": "short",
        "ini_modifier": -2,
        "weight": 7.0,
        "cost": 100,
        "special": "Very large shield. Full-body coverage for ranged attacks (+2 RS). Extremely limited AT. Requires ST 17+.",
        "notes": "Cavalry and siege shield. Door-sized.",
        "related_talents": [],
        "typical_for": ["cavalry"],
        "source": "BRW p. 165",
    },
    {
        "id": "leather_shield",
        "name": "Leather Shield",
        "german_name": "Lederschild",
        "category": "melee",
        "combat_talent": None,
        "is_shield": True,
        "secondary_talents": [],
        "damage": "1d6",
        "at_modifier": -1,
        "pa_modifier": 3,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 2.0,
        "cost": 30,
        "special": "Lightweight shield. +1 PA bonus during Defensive Posture. Shield Smash inflicts only 1 DP.",
        "notes": "Round wooden frame covered with multiple layers of tough leather. Common among riding peoples.",
        "related_talents": [],
        "typical_for": ["novadis", "orcs"],
        "source": "BRW p. 165",
    },
    {
        "id": "large_leather_shield",
        "name": "Large Leather Shield",
        "german_name": "Großer Lederschild",
        "category": "melee",
        "combat_talent": None,
        "is_shield": True,
        "secondary_talents": [],
        "damage": "1d6",
        "at_modifier": -1,
        "pa_modifier": 4,
        "reach_class": "short",
        "ini_modifier": -1,
        "weight": 3.0,
        "cost": 75,
        "special": "Large oval/teardrop leather shield, designed for cavalry use.",
        "notes": "Larger version of the Leather Shield.",
        "related_talents": [],
        "typical_for": ["cavalry", "novadis"],
        "source": "BRW p. 165",
    },
    # ── THROWING WEAPONS (Wurfwaffen) ─────────────────────────────────────
    {
        "id": "throwing_axe",
        "name": "Throwing Axe",
        "german_name": "Wurfbeil",
        "category": "ranged",
        "combat_talent": "throwing_axes",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 1.0,
        "cost": 30,
        "range_bands_schritt_upper": [5, 10, 15, 25, 35],
        "tp_plus_by_range_band": [None, 0, 0, -2, None],
        "distance_class_min": 1,
        "distance_class_max": 8,
        "special": "Can be thrown or used in melee (axes_and_maces talent in melee). Balanced for throwing.",
        "notes": "Light balanced hatchet designed for throwing.",
        "related_talents": ["axes_and_maces"],
        "typical_for": [],
        "source": "BRW p. 163",
    },
    {
        "id": "throwing_knife",
        "name": "Throwing Knife",
        "german_name": "Wurfmesser",
        "category": "ranged",
        "combat_talent": "throwing_knives",
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 0.25,
        "cost": 15,
        "range_bands_schritt_upper": [5, 8, 12, 18, 25],
        "tp_plus_by_range_band": [None, 0, 0, -2, None],
        "distance_class_min": 1,
        "distance_class_max": 6,
        "special": "Light balanced blade for throwing. Can be used in melee as dagger (improvised, -2 AT).",
        "notes": "Usually carried in sets of 3–5.",
        "related_talents": ["daggers"],
        "typical_for": [],
        "source": "BRW p. 163",
    },
    {
        "id": "javelin",
        "name": "Javelin",
        "german_name": "Wurfspeer",
        "category": "ranged",
        "combat_talent": "throwing_spears",
        "secondary_talents": ["spears"],
        "damage": "1d6+5",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 1.5,
        "cost": 25,
        "range_bands_schritt_upper": [8, 15, 25, 40, 55],
        "tp_plus_by_range_band": [None, 0, 0, -2, -4],
        "distance_class_min": 1,
        "distance_class_max": 10,
        "special": "Light throwing spear. Can be used in melee as a spear (spears talent). If caught by enemy, it bends and cannot be re-thrown.",
        "notes": "Standard javelin. Also called pilum in some regions.",
        "related_talents": ["spears"],
        "typical_for": ["infantry", "hunters"],
        "source": "BRW p. 163",
    },
    {
        "id": "bola",
        "name": "Bola",
        "german_name": "Bola",
        "category": "ranged",
        "combat_talent": "throwing_knives",
        "secondary_talents": [],
        "damage": "1d6",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 0.5,
        "cost": 10,
        "range_bands_schritt_upper": [5, 10, 15, 20, 30],
        "tp_plus_by_range_band": [None, 0, 0, -2, None],
        "distance_class_min": 1,
        "distance_class_max": 7,
        "special": "On hit: target must succeed a KK/2 check or be entangled (fallen/immobilized for 1d3 rounds). Low damage but strong control effect.",
        "notes": "Weighted balls on cords. Hunting and combat tool.",
        "related_talents": [],
        "typical_for": ["hunters", "gauchos"],
        "source": "BRW p. 163",
    },
    # ── BOWS (Bogen) ─────────────────────────────────────────────────────
    {
        "id": "short_bow",
        "name": "Short Bow",
        "german_name": "Kurzbogen",
        "category": "ranged",
        "combat_talent": "bows",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 1.0,
        "cost": 40,
        "range_bands_schritt_upper": [10, 20, 35, 60, 100],
        "tp_plus_by_range_band": [None, 0, 0, -2, -4],
        "distance_class_min": 2,
        "distance_class_max": 12,
        "special": "Can be used from horseback. Wind modifiers apply normally.",
        "notes": "Light recurve bow. Easy to carry and conceal.",
        "related_talents": [],
        "typical_for": ["hunters", "scouts"],
        "source": "BRW p. 163",
    },
    {
        "id": "composite_bow",
        "name": "Composite Bow",
        "german_name": "Kompositbogen",
        "category": "ranged",
        "combat_talent": "bows",
        "secondary_talents": [],
        "damage": "1d6+5",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 1.0,
        "cost": 120,
        "range_bands_schritt_upper": [12, 25, 45, 75, 120],
        "tp_plus_by_range_band": [None, 0, 0, -2, -4],
        "distance_class_min": 2,
        "distance_class_max": 14,
        "special": "Can be used from horseback. Slightly longer range than short bow.",
        "notes": "Layered construction of wood, horn, and sinew.",
        "related_talents": [],
        "typical_for": ["cavalry", "novadis", "orcs"],
        "source": "BRW p. 163",
    },
    {
        "id": "long_bow",
        "name": "Long Bow",
        "german_name": "Langbogen",
        "category": "ranged",
        "combat_talent": "bows",
        "secondary_talents": [],
        "damage": "1d6+6",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 2.0,
        "cost": 80,
        "range_bands_schritt_upper": [15, 30, 55, 100, 160],
        "tp_plus_by_range_band": [None, 0, 0, -2, -4],
        "distance_class_min": 3,
        "distance_class_max": 16,
        "special": "Cannot be used from horseback. Requires ST 14+ (else -2 FK). If hit deals > KO/2-2 damage: wound.",
        "notes": "Traditional infantry bow. Requires significant ST and training.",
        "related_talents": [],
        "typical_for": ["militia", "hunters"],
        "source": "BRW p. 163",
    },
    {
        "id": "war_bow",
        "name": "War Bow",
        "german_name": "Kriegsbogen",
        "category": "ranged",
        "combat_talent": "bows",
        "secondary_talents": [],
        "damage": "2d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 2.5,
        "cost": 150,
        "range_bands_schritt_upper": [15, 35, 65, 120, 200],
        "tp_plus_by_range_band": [None, 0, 0, -2, -4],
        "distance_class_min": 3,
        "distance_class_max": 18,
        "special": "Cannot be used from horseback. Requires ST 16+ (else -3 FK). Armor-penetrating: reduce target RS by 1 for damage. If hit deals > KO/2-2: wound.",
        "notes": "Heavy military bow. Short draw time required for reload.",
        "related_talents": [],
        "typical_for": ["elves", "rangers"],
        "source": "BRW p. 163",
    },
    {
        "id": "elf_bow",
        "name": "Elf Bow",
        "german_name": "Elfenbogen",
        "category": "ranged",
        "combat_talent": "bows",
        "secondary_talents": [],
        "damage": "1d6+6",
        "at_modifier": 2,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 1.0,
        "cost": 400,
        "range_bands_schritt_upper": [20, 40, 80, 140, 220],
        "tp_plus_by_range_band": [None, 0, 0, -1, -3],
        "distance_class_min": 2,
        "distance_class_max": 20,
        "special": "+2 FK modifier due to exceptional balance. Can be used from horseback at -2 penalty. If hit deals > KO/2-2: wound.",
        "notes": "Elven masterwork bow. Non-elves use at -2 FK and cannot gain the FK bonus.",
        "related_talents": [],
        "typical_for": ["elves"],
        "source": "BRW p. 163",
    },
    # ── CROSSBOWS (Armbrust) ───────────────────────────────────────────────
    {
        "id": "light_crossbow",
        "name": "Light Crossbow",
        "german_name": "Leichte Armbrust",
        "category": "ranged",
        "combat_talent": "crossbows",
        "secondary_talents": [],
        "damage": "1d6+6",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 3.0,
        "cost": 100,
        "range_bands_schritt_upper": [15, 30, 60, 100, 150],
        "tp_plus_by_range_band": [None, 0, 0, -2, -4],
        "distance_class_min": 3,
        "distance_class_max": 16,
        "special": "Reload: 2 actions. If hit deals > KO/2-2: wound. FK modifier applies normally.",
        "notes": "Crank or stirrup-cocked. Standard militia crossbow.",
        "related_talents": [],
        "typical_for": ["militia", "hunters"],
        "source": "BRW p. 163",
    },
    {
        "id": "heavy_crossbow",
        "name": "Heavy Crossbow",
        "german_name": "Schwere Armbrust",
        "category": "ranged",
        "combat_talent": "crossbows",
        "secondary_talents": [],
        "damage": "2d6+6",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 5.0,
        "cost": 200,
        "range_bands_schritt_upper": [20, 40, 80, 140, 220],
        "tp_plus_by_range_band": [None, 0, 0, -2, -4],
        "distance_class_min": 4,
        "distance_class_max": 20,
        "special": "Reload: 3 actions. Windlass required. If hit deals > KO/2-2: wound. Armor-penetrating: reduce target RS by 2 for damage.",
        "notes": "Windlass-cocked heavy military crossbow.",
        "related_talents": [],
        "typical_for": ["city_guards", "warriors"],
        "source": "BRW p. 163",
    },
    {
        "id": "hand_crossbow",
        "name": "Hand Crossbow",
        "german_name": "Handarmbrust",
        "category": "ranged",
        "combat_talent": "crossbows",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 1.5,
        "cost": 120,
        "range_bands_schritt_upper": [8, 15, 25, 40, 60],
        "tp_plus_by_range_band": [None, 0, 0, -2, None],
        "distance_class_min": 2,
        "distance_class_max": 10,
        "special": "One-handed. Can be used from horseback. Reload: 2 actions. If hit deals > KO/2-2: wound.",
        "notes": "Compact crossbow for concealed carry. Source: AK p. 7.",
        "related_talents": [],
        "typical_for": ["assassins", "scouts"],
        "source": "AK p. 7",
    },
    # ── WdS ADDITIONAL WEAPONS ─────────────────────────────────────────────
    {
        "id": "war_scythe",
        "name": "War Scythe",
        "german_name": "Kriegssense",
        "category": "melee",
        "combat_talent": "infantry_weapons",
        "secondary_talents": [],
        "damage": "2d6+3",
        "at_modifier": 0,
        "pa_modifier": -2,
        "reach_class": "very_long",
        "ini_modifier": -2,
        "weight": 4.0,
        "cost": 50,
        "special": "Two-handed. Can hook and unseat mounted opponents. Difficult to use in tight formations. Attacks from this weapon cannot be parried by daggers.",
        "notes": "Peasant weapon converted for war. Blade mounted upright on long haft.",
        "related_talents": ["spears"],
        "typical_for": ["peasants", "militia"],
        "source": "WdS p. 32",
    },
    {
        "id": "naginata",
        "name": "Naginata",
        "german_name": "Naginata",
        "category": "melee",
        "combat_talent": "infantry_weapons",
        "secondary_talents": ["spears"],
        "damage": "2d6+2",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "very_long",
        "ini_modifier": -1,
        "weight": 3.0,
        "cost": 120,
        "special": "Two-handed. Curved blade on long haft. Better PA than glaive. Used in some eastern Aventuria martial arts.",
        "notes": "Exotic polearm from Thalusian traditions.",
        "related_talents": ["spears"],
        "typical_for": [],
        "source": "WdS p. 32",
    },
    {
        "id": "katar",
        "name": "Katar",
        "german_name": "Katar",
        "category": "melee",
        "combat_talent": "daggers",
        "secondary_talents": [],
        "damage": "1d6+2",
        "at_modifier": 1,
        "pa_modifier": -2,
        "reach_class": "short",
        "ini_modifier": 1,
        "weight": 0.5,
        "cost": 40,
        "special": "Punching dagger. Gripped across palm; the blade extends forward from the fist. +1 AT due to unusual attack angle.",
        "notes": "Common in Novadis and Tulamide regions.",
        "related_talents": [],
        "typical_for": ["novadis"],
        "source": "WdS p. 32",
    },
    {
        "id": "khopesh",
        "name": "Khopesh",
        "german_name": "Khopesh",
        "category": "melee",
        "combat_talent": "sabers",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 0,
        "pa_modifier": -1,
        "reach_class": "medium",
        "ini_modifier": -1,
        "weight": 2.0,
        "cost": 130,
        "special": "Sickle-shaped blade. The hook can catch and disarm: on critical AT, opponent must pass ST check or be disarmed.",
        "notes": "Ancient weapon of Khom desert region.",
        "related_talents": [],
        "typical_for": ["novadis", "tulamides"],
        "source": "WdS p. 33",
    },
    {
        "id": "langsax",
        "name": "Langsax",
        "german_name": "Langsax",
        "category": "melee",
        "combat_talent": "sabers",
        "secondary_talents": ["swords"],
        "damage": "1d6+3",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 1.0,
        "cost": 70,
        "special": "Long single-edged blade, between a long knife and short sword. Can use either Sabers or Swords talent (use whichever is higher).",
        "notes": "Traditional Northlander blade.",
        "related_talents": ["swords"],
        "typical_for": ["thorwal", "northlanders"],
        "source": "WdS p. 33",
    },
    {
        "id": "sai",
        "name": "Sai",
        "german_name": "Sai",
        "category": "melee",
        "combat_talent": "daggers",
        "secondary_talents": [],
        "damage": "1d6",
        "at_modifier": 0,
        "pa_modifier": 3,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 0.75,
        "cost": 35,
        "special": "Metal prong weapon with side tines for catching blades. Excellent PA. Can trap opponent's weapon on successful PA (STR contest to disarm).",
        "notes": "Used in pairs. Primarily a defensive weapon.",
        "related_talents": [],
        "typical_for": [],
        "source": "WdS p. 33",
    },
    {
        "id": "scimitar",
        "name": "Scimitar",
        "german_name": "Krummschwert",
        "category": "melee",
        "combat_talent": "sabers",
        "secondary_talents": [],
        "damage": "1d6+4",
        "at_modifier": 1,
        "pa_modifier": -1,
        "reach_class": "medium",
        "ini_modifier": 0,
        "weight": 1.75,
        "cost": 110,
        "special": "Broadly curved heavy saber. High AT modifier. Common cavalry weapon.",
        "notes": "Broader and heavier curve than shamshir.",
        "related_talents": [],
        "typical_for": ["novadis", "cavalry"],
        "source": "WdS p. 33",
    },
    {
        "id": "lasso",
        "name": "Lasso",
        "german_name": "Wurflasso",
        "category": "ranged",
        "combat_talent": "throwing_knives",
        "secondary_talents": [],
        "damage": "0",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": None,
        "ini_modifier": 0,
        "weight": 0.5,
        "cost": 10,
        "range_bands_schritt_upper": [3, 7, 12, 15, 20],
        "tp_plus_by_range_band": [None, 0, None, None, None],
        "distance_class_min": 1,
        "distance_class_max": 6,
        "special": "Does no damage. On hit: target is entangled (falls prone, can act but at -2 AT/PA until freed). Target must pass STR check vs. thrower's AT roll to free self each round.",
        "notes": "Rope with weighted loop. Cowboy/Novadis tool.",
        "related_talents": [],
        "typical_for": ["novadis", "gaucho"],
        "source": "WdS p. 34",
    },
    # ── AK ADDITIONAL WEAPONS ─────────────────────────────────────────────
    {
        "id": "whip",
        "name": "Whip",
        "german_name": "Peitsche",
        "category": "melee",
        "combat_talent": "chain_weapons",
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": 2,
        "pa_modifier": -4,
        "reach_class": "very_long",
        "ini_modifier": 0,
        "weight": 0.5,
        "cost": 15,
        "special": "Attack only — cannot parry. High AT modifier, very long reach. On hit can cause pain/distraction in addition to damage. Ignores shield PA bonus.",
        "notes": "Leather or braided cord. Usually attack-only weapon.",
        "related_talents": [],
        "typical_for": [],
        "source": "AK p. 12",
    },
    {
        "id": "scourge",
        "name": "Scourge",
        "german_name": "Geißel",
        "category": "melee",
        "combat_talent": "chain_weapons",
        "secondary_talents": [],
        "damage": "1d6+2",
        "at_modifier": 1,
        "pa_modifier": -3,
        "reach_class": "long",
        "ini_modifier": -1,
        "weight": 1.0,
        "cost": 20,
        "special": "Multi-thong flail. Attack only — cannot parry. Ignores shield PA bonus. All parries suffer +2 difficulty.",
        "notes": "Multiple leather straps with knotted ends.",
        "related_talents": [],
        "typical_for": [],
        "source": "AK p. 12",
    },
    {
        "id": "hook_sword",
        "name": "Hook Sword",
        "german_name": "Hakenschwert",
        "category": "melee",
        "combat_talent": "swords",
        "secondary_talents": ["fencing_weapons"],
        "damage": "1d6+3",
        "at_modifier": 0,
        "pa_modifier": 1,
        "reach_class": "medium",
        "ini_modifier": 0,
        "weight": 1.5,
        "cost": 90,
        "special": "Blade with hooked tip for catching and disarming. On successful PA: may attempt disarm (STR contest). Can be linked in pairs for extended reach. From AK.",
        "notes": "Exotic blade. Usable with swords or fencing weapons (use whichever is higher).",
        "related_talents": ["fencing_weapons"],
        "typical_for": [],
        "source": "AK p. 11",
    },
    {
        "id": "kama",
        "name": "Kama",
        "german_name": "Kama",
        "category": "melee",
        "combat_talent": "axes_and_maces",
        "secondary_talents": ["chain_weapons"],
        "damage": "1d6+3",
        "at_modifier": 0,
        "pa_modifier": -1,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 0.75,
        "cost": 35,
        "special": "Short sickle-like blade. Can be used with axes_and_maces or chain_weapons. When chained (kusarigama): use chain_weapons talent, gains chain properties.",
        "notes": "Farming tool adapted as weapon.",
        "related_talents": ["chain_weapons"],
        "typical_for": [],
        "source": "AK p. 11",
    },
    {
        "id": "main_gauche",
        "name": "Main Gauche",
        "german_name": "Linkhand",
        "category": "melee",
        "combat_talent": "daggers",
        "secondary_talents": [],
        "damage": "1d6+1",
        "at_modifier": -1,
        "pa_modifier": 3,
        "reach_class": "short",
        "ini_modifier": 0,
        "weight": 0.5,
        "cost": 60,
        "special": "Left-hand parrying dagger. Counts as parrying weapon. Superior PA to standard parrying dagger. Side-bars catch opponent blades.",
        "notes": "Designed for fencing style: rapier in right hand, main gauche in left.",
        "related_talents": [],
        "typical_for": ["duelists", "fencers"],
        "source": "AK p. 10",
    },
    {
        "id": "warhorse_lance",
        "name": "Lance",
        "german_name": "Lanze",
        "category": "melee",
        "combat_talent": "jousting",
        "secondary_talents": ["spears"],
        "damage": "2d6+4",
        "at_modifier": 0,
        "pa_modifier": 0,
        "reach_class": "very_long",
        "ini_modifier": 0,
        "weight": 4.0,
        "cost": 80,
        "special": "Couched lance charge: uses Jousting talent (AT only, cannot parry). When used on foot as spear: uses Spears talent at -2 AT. Charge damage multiplied by mount speed factor.",
        "notes": "Both tournament and war lances use Jousting talent when mounted.",
        "related_talents": ["spears"],
        "typical_for": ["cavalry", "knights"],
        "source": "BRW p. 164 / WdS p. 101",
    },
]

# ===========================================================================
# ARMOR DATA (BRW pp. 165–167 + AK armor entries)
# ===========================================================================
ARMOR_DATA = [
    # ── LIGHT ARMOR ──────────────────────────────────────────────────────
    {
        "id": "thick_clothing",
        "name": "Thick Clothing",
        "german_name": "Dicke Kleidung",
        "category": "light",
        "ar": 1,
        "ec": 1,
        "ini_modifier": 0,
        "coverage": ["torso", "arms", "legs"],
        "weight": 3.0,
        "cost": 30,
        "special": "RS does not add to armor worn over it. Includes winter/fur clothing, all-leather wilderness clothing, heavy leather jackets, thick brocade and velvet garments.",
        "magic_restriction": False,
        "source": "BRW p. 165",
    },
    {
        "id": "quilted_underclothing",
        "name": "Quilted Underclothing",
        "german_name": "Wattierte Unterkleidung",
        "category": "light",
        "ar": 1,
        "ec": 1,
        "ini_modifier": 0,
        "coverage": ["torso", "arms", "legs"],
        "weight": 2.5,
        "cost": 25,
        "special": "Required under all metal armor to prevent abrasions. RS and BE do not add to armor worn over it when worn alone.",
        "magic_restriction": False,
        "source": "BRW p. 165",
    },
    {
        "id": "quilted_surcoat",
        "name": "Quilted Surcoat (Gambeson)",
        "german_name": "Wattierter Waffenrock",
        "category": "light",
        "ar": 2,
        "ec": 2,
        "ini_modifier": 0,
        "coverage": ["torso", "arms"],
        "weight": 3.0,
        "cost": 40,
        "special": "Two layers of coarse linen stitched with padding. RS and BE add to armor worn over it.",
        "magic_restriction": False,
        "source": "BRW p. 165",
    },
    {
        "id": "toadskin",
        "name": "Toadskin",
        "german_name": "Krötenhaut",
        "category": "light",
        "ar": 3,
        "ec": 2,
        "ini_modifier": -1,
        "coverage": ["torso"],
        "weight": 4.0,
        "cost": 60,
        "special": "Vest of thick leather with heavy rivets. EC not added to Swimming or Balance checks. Only RS 2 vs. ranged.",
        "magic_restriction": False,
        "source": "BRW p. 165",
    },
    {
        "id": "leather_harness",
        "name": "Leather Harness",
        "german_name": "Lederharnisch",
        "category": "light",
        "ar": 3,
        "ec": 3,
        "ini_modifier": 0,
        "coverage": ["torso", "arms", "legs"],
        "weight": 8.0,
        "cost": 80,
        "special": "Hardened and lacquered leather. Covers more than toadskin. Standard light armor.",
        "magic_restriction": False,
        "source": "BRW p. 165",
    },
    {
        "id": "studded_leather",
        "name": "Studded Leather",
        "german_name": "Genietetes Leder",
        "category": "light",
        "ar": 4,
        "ec": 3,
        "ini_modifier": 0,
        "coverage": ["torso", "arms", "legs"],
        "weight": 10.0,
        "cost": 100,
        "special": "Leather with metal studs. Higher RS than plain leather. Popular among bandits and mercenaries.",
        "magic_restriction": False,
        "source": "BRW p. 165",
    },
    # ── MEDIUM ARMOR ──────────────────────────────────────────────────────
    {
        "id": "scale_armor",
        "name": "Scale Armor",
        "german_name": "Schuppenpanzer",
        "category": "medium",
        "ar": 5,
        "ec": 4,
        "ini_modifier": -1,
        "coverage": ["torso", "arms", "legs"],
        "weight": 15.0,
        "cost": 200,
        "special": "Overlapping metal or horn scales sewn to leather backing. RS stacks with quilted underclothing.",
        "magic_restriction": True,
        "source": "BRW p. 165",
    },
    {
        "id": "chain_hauberk",
        "name": "Chain Hauberk",
        "german_name": "Kettenhemd",
        "category": "medium",
        "ar": 5,
        "ec": 4,
        "ini_modifier": -1,
        "coverage": ["torso", "arms"],
        "weight": 15.0,
        "cost": 250,
        "special": "Chain mail shirt. Requires quilted underclothing (BE +1, RS +1 when worn together). Metal: interferes with arcane magic.",
        "magic_restriction": True,
        "source": "BRW p. 165",
    },
    {
        "id": "full_chain",
        "name": "Full Chain",
        "german_name": "Kettenrüstung",
        "category": "medium",
        "ar": 6,
        "ec": 5,
        "ini_modifier": -1,
        "coverage": ["torso", "arms", "legs"],
        "weight": 20.0,
        "cost": 400,
        "special": "Complete chain mail suit including coif. Requires quilted underclothing. Metal: arcane magic penalty.",
        "magic_restriction": True,
        "source": "BRW p. 166",
    },
    {
        "id": "half_plate",
        "name": "Half Plate",
        "german_name": "Halbrüstung",
        "category": "medium",
        "ar": 7,
        "ec": 5,
        "ini_modifier": -2,
        "coverage": ["torso", "arms", "legs"],
        "weight": 22.0,
        "cost": 600,
        "special": "Combination of plate sections and chain. Better protection than full chain, less than full plate. Metal: arcane magic penalty.",
        "magic_restriction": True,
        "source": "BRW p. 166",
    },
    # ── HEAVY ARMOR ───────────────────────────────────────────────────────
    {
        "id": "plate_cuirass",
        "name": "Plate Cuirass",
        "german_name": "Kürass",
        "category": "heavy",
        "ar": 7,
        "ec": 4,
        "ini_modifier": -2,
        "coverage": ["torso"],
        "weight": 12.0,
        "cost": 500,
        "special": "Solid breastplate and backplate only. Worn over quilted surcoat. RS and BE add together. Metal: arcane magic penalty.",
        "magic_restriction": True,
        "source": "BRW p. 166",
    },
    {
        "id": "three_quarter_plate",
        "name": "Three-Quarter Plate",
        "german_name": "Dreiviertelharnisch",
        "category": "heavy",
        "ar": 8,
        "ec": 6,
        "ini_modifier": -2,
        "coverage": ["torso", "arms", "legs"],
        "weight": 25.0,
        "cost": 1000,
        "special": "Plate covering torso, arms, and thighs. Usually worn with quilted underclothing (+1 RS, +1 BE). Metal: arcane magic penalty.",
        "magic_restriction": True,
        "source": "BRW p. 166",
    },
    {
        "id": "full_plate",
        "name": "Full Plate",
        "german_name": "Plattenharnisch",
        "category": "heavy",
        "ar": 9,
        "ec": 6,
        "ini_modifier": -3,
        "coverage": ["torso", "arms", "legs", "head"],
        "weight": 30.0,
        "cost": 2500,
        "special": "Complete plate armor including helm. Must be custom-fitted. Requires quilted underclothing. Metal: arcane magic penalty. Cannot swim.",
        "magic_restriction": True,
        "source": "BRW p. 166",
    },
    {
        "id": "jousting_armor",
        "name": "Jousting Armor",
        "german_name": "Turnierharnisch",
        "category": "heavy",
        "ar": 11,
        "ec": 8,
        "ini_modifier": -4,
        "coverage": ["torso", "arms", "legs", "head"],
        "weight": 40.0,
        "cost": 5000,
        "special": "Specialized tournament plate. Extremely heavy. Only practical on horseback for jousting. Cannot dodge or sprint. Metal: arcane magic penalty.",
        "magic_restriction": True,
        "source": "BRW p. 167",
    },
    # ── HELMETS (+RS additive) ──────────────────────────────────────────────
    {
        "id": "open_helm",
        "name": "Open Helm",
        "german_name": "Offener Helm",
        "category": "helmet",
        "ar": 2,
        "ec": 1,
        "ini_modifier": -1,
        "coverage": ["head"],
        "weight": 1.5,
        "cost": 40,
        "special": "+RS only to head. Add to body armor RS for head-hit calculations. No vision restriction.",
        "magic_restriction": True,
        "source": "BRW p. 166",
    },
    {
        "id": "closed_helm",
        "name": "Closed Helm",
        "german_name": "Geschlossener Helm",
        "category": "helmet",
        "ar": 4,
        "ec": 2,
        "ini_modifier": -2,
        "coverage": ["head"],
        "weight": 3.0,
        "cost": 100,
        "special": "+RS only to head. Reduces vision arc: -1 AT, +1 BE while worn. Muffles hearing: -2 to all perception checks.",
        "magic_restriction": True,
        "source": "BRW p. 166",
    },
    {
        "id": "great_helm",
        "name": "Great Helm",
        "german_name": "Topfhelm",
        "category": "helmet",
        "ar": 6,
        "ec": 3,
        "ini_modifier": -3,
        "coverage": ["head"],
        "weight": 5.0,
        "cost": 200,
        "special": "+RS only to head. Severely restricts vision: -2 AT for ranged attacks aimed at head not possible. -3 to all perception checks.",
        "magic_restriction": True,
        "source": "BRW p. 166",
    },
    # ── LIMB PROTECTION (+RS additive) ────────────────────────────────────
    {
        "id": "arm_guards",
        "name": "Arm Guards",
        "german_name": "Armschienen",
        "category": "limb_armor",
        "ar": 2,
        "ec": 1,
        "ini_modifier": 0,
        "coverage": ["arms"],
        "weight": 2.0,
        "cost": 60,
        "special": "+RS to arms only. Add to body armor RS for arm-hit calculations.",
        "magic_restriction": True,
        "source": "BRW p. 167",
    },
    {
        "id": "leg_guards",
        "name": "Leg Guards",
        "german_name": "Beinschienen",
        "category": "limb_armor",
        "ar": 2,
        "ec": 1,
        "ini_modifier": 0,
        "coverage": ["legs"],
        "weight": 2.5,
        "cost": 60,
        "special": "+RS to legs only. Add to body armor RS for leg-hit calculations.",
        "magic_restriction": True,
        "source": "BRW p. 167",
    },
    {
        "id": "gauntlets",
        "name": "Gauntlets",
        "german_name": "Panzerhandschuhe",
        "category": "limb_armor",
        "ar": 1,
        "ec": 1,
        "ini_modifier": 0,
        "coverage": ["hands"],
        "weight": 1.0,
        "cost": 40,
        "special": "+RS to hands. Unarmed punch damage increases by +1 DP. Fine manipulations: -1 penalty.",
        "magic_restriction": True,
        "source": "BRW p. 167",
    },
    # ── AK ADDITIONAL ARMOR ────────────────────────────────────────────────
    {
        "id": "brigandine",
        "name": "Brigandine",
        "german_name": "Brigantine",
        "category": "medium",
        "ar": 6,
        "ec": 4,
        "ini_modifier": -1,
        "coverage": ["torso", "arms"],
        "weight": 14.0,
        "cost": 300,
        "special": "Metal plates riveted inside leather or cloth cover. Less visible than chain. RS and BE stack with quilted underclothing. Metal: arcane magic penalty.",
        "magic_restriction": True,
        "source": "AK p. 18",
    },
    {
        "id": "lamellar",
        "name": "Lamellar Armor",
        "german_name": "Lamellenrüstung",
        "category": "medium",
        "ar": 6,
        "ec": 4,
        "ini_modifier": -1,
        "coverage": ["torso", "arms", "legs"],
        "weight": 16.0,
        "cost": 350,
        "special": "Horizontal rows of lacquered plates laced together. Eastern Aventuria style. Metal: arcane magic penalty.",
        "magic_restriction": True,
        "source": "AK p. 18",
    },
    {
        "id": "coat_of_plates",
        "name": "Coat of Plates",
        "german_name": "Plattenrock",
        "category": "medium",
        "ar": 7,
        "ec": 5,
        "ini_modifier": -2,
        "coverage": ["torso"],
        "weight": 18.0,
        "cost": 450,
        "special": "Large plates riveted to leather coat covering torso only. Between brigandine and plate cuirass. Metal: arcane magic penalty.",
        "magic_restriction": True,
        "source": "AK p. 18",
    },
]

# ===========================================================================
# VALIDATION
# ===========================================================================
def validate_weapons(weapons):
    errors = []
    ids_seen = set()
    for w in weapons:
        wid = w["id"]
        if wid in ids_seen:
            errors.append(f"Duplicate weapon id: {wid!r}")
        ids_seen.add(wid)
        ct = w.get("combat_talent")
        if ct and ct not in VALID_TALENT_IDS:
            errors.append(f"Weapon {wid!r}: invalid combat_talent {ct!r}")
        for st in w.get("secondary_talents", []):
            if st not in VALID_TALENT_IDS:
                errors.append(f"Weapon {wid!r}: invalid secondary_talent {st!r}")
    return errors

def validate_armor(armors):
    errors = []
    ids_seen = set()
    for a in armors:
        aid = a["id"]
        if aid in ids_seen:
            errors.append(f"Duplicate armor id: {aid!r}")
        ids_seen.add(aid)
    return errors

# ===========================================================================
# BUILD OUTPUT JSON
# ===========================================================================
def build_weapons_json(weapons):
    return {
        "meta": {
            "schema_version": "2.0",
            "last_updated": "2026-05-05",
            "source_books": [
                "DSA 4.1 Basisregelwerk (BRW)",
                "Arsenal Kompendium (AK)",
                "Wege des Schwertes (WdS)",
            ],
            "notes": (
                "Weights in Stein (1 Stein = 1 kg). Prices in Silbertaler. "
                "Source AA (Aventuria Armory) excluded — TDE5 system. "
                "secondary_talents: weapon can be used with these talents in addition to combat_talent."
            ),
            "ranged_and_throwing": {
                "pdf_sources_for_range_bands": [
                    "tde_german_rules (DSA 4.1 Basisregelwerk): Aventurische Schuss- und Wurfwaffen p.163; Entfernung/Reichweiteklassen p.152-155.",
                    "arsenal_kompendium: Schuss- und Wurfwaffen pp.6-7.",
                ],
                "distance_class_span": "distance_class_min / distance_class_max: inclusive Entfernungsklassen (EK) span from BRW combat grid.",
                "reichweiteklassen_order": ["sehr_nah", "nah", "mittel", "weit", "extrem_weit"],
                "range_bands_schritt_upper_note": (
                    "range_bands_schritt_upper: five upper inclusive limits in Schritt, "
                    "matching reichweiteklassen_order. BRW p.153."
                ),
                "tp_plus_by_range_band_note": (
                    "tp_plus_by_range_band: optional TP shifts. null = em-dash in BRW table (not applicable)."
                ),
                "fernkampf_fk_modifiers_by_reichweiteklasse_BRW": {
                    "sehr_nah": -2,
                    "nah": 0,
                    "mittel": 4,
                    "weit": 8,
                    "extrem_weit": 12,
                },
            },
        },
        "weapons": weapons,
    }

def build_armor_json(armors):
    return {
        "meta": {
            "schema_version": "2.0",
            "last_updated": "2026-05-05",
            "source_books": [
                "DSA 4.1 Basisregelwerk (BRW)",
                "Arsenal Kompendium (AK)",
                "Wege des Schwertes (WdS)",
            ],
            "notes": (
                "RS = Rüstungsschutz (Armor Rating). BE = Behinderung (Encumbrance). "
                "Weights in Stein (1 Stein = 1 kg). Prices in Silbertaler. "
                "Helmet/limb armor: +RS additive to body armor. "
                "Metal armor interferes with arcane magic (see magic_restriction). "
                "Source AA (Aventuria Armory) excluded — TDE5 system."
            ),
        },
        "armor": armors,
    }

# ===========================================================================
# MAIN
# ===========================================================================
def main():
    print("TDE 4.1 Gear Extraction — BRW + AK + WdS")
    print("=" * 50)

    # Validate
    weapon_errors = validate_weapons(WEAPONS_DATA)
    armor_errors = validate_armor(ARMOR_DATA)

    all_errors = weapon_errors + armor_errors
    if all_errors:
        print("\nVALIDATION ERRORS:")
        for e in all_errors:
            print(f"  ERROR: {e}")
        print(f"\n{len(all_errors)} error(s) found. Fix before writing output.")
        sys.exit(1)

    print(f"  Weapons: {len(WEAPONS_DATA)} entries — OK")
    print(f"  Armor:   {len(ARMOR_DATA)} entries — OK")
    print("  All talent references valid.")

    # Write weapons
    weapons_path = ROOT / "data" / "equipment" / "weapons.json"
    weapons_json = build_weapons_json(WEAPONS_DATA)
    with open(weapons_path, "w", encoding="utf-8") as f:
        json.dump(weapons_json, f, ensure_ascii=False, indent=2)
    print(f"\nWrote: {weapons_path}")

    # Write armor
    armor_path = ROOT / "data" / "equipment" / "armor.json"
    armor_json = build_armor_json(ARMOR_DATA)
    with open(armor_path, "w", encoding="utf-8") as f:
        json.dump(armor_json, f, ensure_ascii=False, indent=2)
    print(f"Wrote: {armor_path}")

    print("\nDone.")

if __name__ == "__main__":
    main()
